pipeline {
    agent any 

    environment {
        DOCKER_IMAGE = 'capstone-project'
        DOCKER_TAG = "latest"
        CONTAINER_NAME = 'capstone-project-prod'
        CONTAINER_PORT = 80
        HOST_PORT = 80
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    if (isUnix()) {
                        sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} -f fe/Dockerfile"
                    } else {
                        powershell "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove the container if it is already running
                    if (isUnix()) {
                        sh "if [ \$(docker ps -q --filter name=${env.CONTAINER_NAME}) ]; then docker stop ${env.CONTAINER_NAME}; docker rm ${env.CONTAINER_NAME}; fi"
                        
                    } else {
                       powershell "If (docker ps -q --filter name=${env.CONTAINER_NAME}) {docker stop ${env.CONTAINER_NAME}; docker rm ${env.CONTAINER_NAME}}"
                    }

                    // Launch the new container
                    if (isUnix()) {
                        sh "docker run -d --name ${env.CONTAINER_NAME} -p ${env.HOST_PORT}:${env.CONTAINER_PORT} ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    } else {
                        powershell "docker run -d --name ${env.CONTAINER_NAME} -p ${env.HOST_PORT}:${env.CONTAINER_PORT} ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    }
                }
            }
        }
    }
}
