# Generated by Django 5.0.6 on 2024-06-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=255)),
                ('GroupDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=255)),
                ('ProjectDescription', models.TextField()),
                ('ProjectOwner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=255, unique=True)),
                ('Passwd', models.CharField(max_length=255)),
                ('UserRole', models.IntegerField(blank=True, choices=[(1, 'student'), (2, 'client'), (3, 'tut'), (4, 'cord'), (5, 'admin')], default=1, null=True)),
                ('UserInformation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProjectsLink',
            fields=[
                ('GroupProjectsLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPreferencesLink',
            fields=[
                ('GroupPreferencesLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='myapp.user'),
        ),
        migrations.CreateModel(
            name='GroupUsersLink',
            fields=[
                ('GroupUsersLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='UserPreferencesLink',
            fields=[
                ('UserPreferencesLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
