# Generated by Django 5.0.6 on 2024-07-01 13:22
from django.db import migrations
from django.contrib.auth.hashers import make_password

def add_roles(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    stu=User.objects.create(FirstName='stu', LastName='stu',EmailAddress="stu@stu.com",Passwd=make_password("stu"),UserRole=1,UserInformation="")
    stu.save()
    cord=User.objects.create(FirstName='cord', LastName='cord',EmailAddress="cord@cord.com",Passwd=make_password("cord"),UserRole=4,UserInformation="")
    cord.save()
    cli=User.objects.create(FirstName='cli', LastName='cli',EmailAddress="cli@cli.com",Passwd=make_password("cli"),UserRole=2,UserInformation="")
    cli.save()
    admin=User.objects.create(FirstName='admin', LastName='admin',EmailAddress="admin@admin.com",Passwd=make_password("admin"),UserRole=5,UserInformation="")
    admin.save()
    tut=User.objects.create(FirstName='tut', LastName='tut',EmailAddress="tut@tut.com",Passwd=make_password("tut"),UserRole=3,UserInformation="")
    tut.save()
    print("=====================================")
    print("admin created")
    print("tut created")
    print("stu created")
    print("cord created")
    print("cli created")
    

                        
class Migration(migrations.Migration):

    dependencies =[( 'myapp', '0001_initial')
    ]
    
    operations = [
        migrations.RunPython(add_roles),
    ]
