# Generated by Django 5.0.6 on 2024-07-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('SkillId', models.AutoField(primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Project',
            fields=[
                ('SKillProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('SkillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skill')),
            ],
        ),
    ]
