# Generated by Django 5.0.6 on 2024-06-25 08:10

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
def add_roles(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    admin=User.objects.create(FirstName='admin', LastName='admin',EmailAddress="admin@admin.com",Passwd=make_password("admin"),UserRole=5,UserInformation="")
    admin.save()
    print("admin created")
    

                        
class Migration(migrations.Migration):


    dependencies =[( 'myapp', '0001_initial')
    ]
    
    operations = [
        migrations.RunPython(add_roles),
    ]
