# Generated by Django 5.0.6 on 2024-06-25 08:10
from django.db import migrations
from django.contrib.auth.hashers import make_password
def add_roles(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    stu=User.objects.create(FirstName='stu', LastName='stu',EmailAddress="stu@stu.com",Passwd=make_password("stu"),UserRole=1,UserInformation="")
    stu.save()
    cord=User.objects.create(FirstName='cord', LastName='cord',EmailAddress="cord@cord.com",Passwd=make_password("cord"),UserRole=4,UserInformation="")
    cord.save()
    cli=User.objects.create(FirstName='cli', LastName='cli',EmailAddress="cli@cli.com",Passwd=make_password("cli"),UserRole=2,UserInformation="")
    cli.save()
    print("stu created")
    print("cord created")
    print("cli created")
    

                        
class Migration(migrations.Migration):

    dependencies =[( 'myapp', '0002_add_admin_tut')
    ]
    
    operations = [
        migrations.RunPython(add_roles),
    ]
