# Generated by Django 5.0.6 on 2024-07-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_test_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppreference',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='groupskillevaluation',
            name='lock',
        ),
        migrations.AlterField(
            model_name='grouppreference',
            name='Rank',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AddField(
            model_name='grouppreference',
            name='Lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
