# Generated by Django 5.0.6 on 2024-06-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_admin_tut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interestId', models.AutoField(primary_key=True, serialize=False)),
                ('interest_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='MaxNumof_group',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('skillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.interest')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
