# Generated by Django 5.0.6 on 2024-07-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_test_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuserslink',
            unique_together={('UserID', 'GroupID')},
        ),
    ]
