# Generated by Django 5.0.6 on 2024-07-02 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserRole',
            field=models.IntegerField(blank=True, choices=[(1, 'student'), (2, 'client'), (3, 'tut'), (4, 'cord'), (5, 'admin')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='GroupAssignProject',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('AllocatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProgressStatus', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('Allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('AdditionalData', models.JSONField(blank=True, null=True)),
                ('IsRead', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ReceiverUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='myapp.user')),
                ('SenderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='myapp.user')),
            ],
        ),
    ]
