# Generated by Django 5.0.6 on 2024-07-26 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_insert_test_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("AllocationID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.group"
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("SubmissionID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SubmissionTime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "SubmissionDemoVideo",
                    models.FileField(blank=True, null=True, upload_to="demos/"),
                ),
                (
                    "SubmissionReport",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("GithubLink", models.URLField(blank=True, null=True)),
                (
                    "Group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.group"
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.project"
                    ),
                ),
                (
                    "SubmitBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
