# Generated by Django 5.0.6 on 2024-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserRole',
            field=models.IntegerField(blank=True, choices=[(1, 'student'), (2, 'client'), (3, 'tut'), (4, 'cord'), (5, 'admin')], default=1, null=True),
        ),
    ]
