# Generated by Django 5.0.6 on 2024-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_skill_skill_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='SkillId',
            new_name='SkillID',
        ),
        migrations.RenameField(
            model_name='skill_project',
            old_name='SKillProjectId',
            new_name='SkillProjectID',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectGroupNumber',
            field=models.IntegerField(default=0),
        ),
    ]
