# Generated by Django 5.0.6 on 2024-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
