# Generated by Django 5.0.6 on 2024-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_admin_tut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectOwner',
            field=models.CharField(max_length=255),
        ),
    ]
