# Generated by Django 5.0.6 on 2024-07-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='GroupMembers',
            field=models.ManyToManyField(through='myapp.GroupUsersLink', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to='myapp.user'),
        ),
    ]
