# Generated by Django 5.0.6 on 2024-07-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_area_areaname_alter_user_userrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ReceiverUser',
        ),
        migrations.AddField(
            model_name='user',
            name='Areas',
            field=models.ManyToManyField(through='myapp.StudentArea', to='myapp.area'),
        ),
        migrations.CreateModel(
            name='NotificationReceiver',
            fields=[
                ('NotificationReceiverID', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notification')),
                ('ReceiverUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Notifications',
            field=models.ManyToManyField(through='myapp.NotificationReceiver', to='myapp.notification'),
        ),
    ]
