# Generated by Django 5.0.6 on 2024-07-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_grouppreference_lock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender_object_id',
        ),
        migrations.RemoveField(
            model_name='notificationreceiver',
            name='ReceiverUser',
        ),
        migrations.AddField(
            model_name='notification',
            name='FromGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='FromUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='Receivers',
            field=models.ManyToManyField(related_name='notifications_received', through='myapp.NotificationReceiver', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='notificationreceiver',
            name='Receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='Type',
            field=models.CharField(choices=[('personal', 'personal'), ('group', 'group')], max_length=255),
        ),
    ]
