# Generated by Django 5.0.6 on 2024-06-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_interest_skill_project_maxnumof_group_skillgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interestId',
            new_name='InterestID',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='interest_name',
            new_name='InterestName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='MaxNumof_group',
            new_name='MaxNumOfGroup',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='id',
            new_name='SkillID',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='SkillName',
        ),
        migrations.RenameField(
            model_name='skillgroup',
            old_name='groupId',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='skillgroup',
            old_name='skillId',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skillgroup',
            old_name='id',
            new_name='SkillGroupID',
        ),
        migrations.RenameField(
            model_name='skillproject',
            old_name='projectId',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='skillproject',
            old_name='skillId',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='skillproject',
            old_name='id',
            new_name='SkillProjectID',
        ),
        migrations.RenameField(
            model_name='studentinterest',
            old_name='interestId',
            new_name='Interest',
        ),
        migrations.RenameField(
            model_name='studentinterest',
            old_name='id',
            new_name='StudentInterestID',
        ),
        migrations.RenameField(
            model_name='studentinterest',
            old_name='userid',
            new_name='User',
        ),
    ]
