# Generated by Django 5.0.6 on 2024-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_area_areaname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='MaxMemberNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserRole',
            field=models.IntegerField(blank=True, choices=[(1, 'student'), (2, 'client'), (3, 'tut'), (4, 'cord'), (5, 'admin')], default=1, null=True),
        ),
    ]
