# Generated by Django 5.0.6 on 2024-07-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_groupuserslink_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupprojectslink',
            unique_together={('GroupID', 'ProjectID')},
        ),
    ]
