# Generated by Django 5.0.6 on 2024-07-02 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_area_areaname_alter_user_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAssignProject',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('AllocatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProgressStatus', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('Allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
