# Generated by Django 5.0.6 on 2024-07-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_notification_receiveruser_user_areas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationreceiver',
            old_name='NotificationID',
            new_name='Notification',
        ),
    ]
