# Generated by Django 5.0.6 on 2024-07-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0005_rename_notificationid_notificationreceiver_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='IsRead',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='SenderUser',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationreceiver',
            name='IsRead',
            field=models.BooleanField(default=False),
        ),
    ]
