# Generated by Django 5.0.6 on 2024-07-05 03:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0006_remove_notification_isread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReceiver',
            fields=[
                ('MessageReceiverID', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_object_id', models.PositiveIntegerField()),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.message')),
                ('receiver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
