# Generated by Django 5.0.6 on 2024-07-07 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_notification_isread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('IsFixed', models.BooleanField(default=False)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='myapp.user')),
                ('ContactUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('Contact', 'ContactUser')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Contacts',
            field=models.ManyToManyField(through='myapp.Contact', to='myapp.user'),
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('GroupMessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ReadBy', models.ManyToManyField(related_name='read_group_messages', to='myapp.user')),
                ('ReceiverGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages', to='myapp.group')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsRead', models.BooleanField()),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='myapp.user')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.user')),
            ],
        ),
    ]
