# Generated by Django 5.0.6 on 2024-07-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact_user_contacts_groupmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferenceslink',
            name='ProjectID',
        ),
        migrations.RemoveField(
            model_name='userpreferenceslink',
            name='UserID',
        ),
        migrations.CreateModel(
            name='GroupPreference',
            fields=[
                ('PreferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Rank', models.IntegerField()),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('Preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Preferences',
            field=models.ManyToManyField(through='myapp.GroupPreference', to='myapp.project'),
        ),
        migrations.DeleteModel(
            name='GroupPreferencesLink',
        ),
        migrations.DeleteModel(
            name='UserPreferencesLink',
        ),
    ]
