# Generated by Django 5.0.6 on 2024-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userpreferenceslink_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='MaxMemberNumber',
            field=models.IntegerField(default=1),
        ),
    ]
